name: wasalni
description: Wasalni - Smart transportation platform.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Backend / Authentication / Database / Realtime
  supabase_flutter: ^2.17.2

  # Navigation
  go_router: ^18.0.1

  # Networking
  dio: ^5.11.0

  # Maps
  flutter_map: ^8.3.2
  latlong2: ^0.9.1

  # GPS / Location
  geolocator: ^14.0.3

  # Local secure storage
  flutter_secure_storage: ^10.0.0

  # Local preferences
  shared_preferences: ^2.5.3

  # State management
  flutter_riverpod: ^3.0.3

  # Formatting
  intl: ^0.20.2

  # Unique IDs
  uuid: ^4.5.1

  # Images
  image_picker: ^1.2.1

  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
